export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: 'Anvil Inc.',
  description: 'Generated by create next app',
  websiteUrl: 'https://anvilinc.vercel.app/',
  contactEmailAddress: 'info@domain.com',
};
