import { headers } from 'next/headers';

export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: 'Anvil Inc.',
  description: 'Generated by create next app',
  websiteUrl: `https://${headers().get('host')}`,
  contactEmailAddress: `info@${headers().get('host')}`,
};
